# Configuration file for the CLI module.
deterministic = true

# The "args" group permits to define the default values for any argument. Note that
# default values are overwritten if another value is passed from the command line
# interface. Sub-groups are arbitrary and used only to ease organisation for humans.
[args.data]
batch_size = 64
num_workers = 4

[args.flags]
checkpoints = false

[args.loggers]
name = ""
project = ""
wandb = false

[args.paths]
checkpoints_dir = "./models/checkpoints/"
data_dir = "./datasets/processed/"
images_dir = "./media/images/"
raw_data_dir = "./datasets/raw/"

[args.trainer]
accelerator = "gpu"
gpus = "0"
precision = 16

# The "environment" group permits to define environmental variables.
[environment]
CUDA_VISIBLE_DEVICES = 0
WANDB_API_KEY = ""
